### ISSUE TITLE
Nicenboim and Vasishth 2016

### ISSUE THREAD

**Issue by vasishth** [vasishth/BayesLMMTutorial#6]
Are we going to get into trouble for citing Nicenboim and Vasishth 2016? There we also introduce Bayesian methods, but don't use Stan proper (rstanarm). I see our paper as very different in aim from NV16. Do you guys agree? If there is too much overlap in your opinion I can drop all citations to it. I added some citations to it because we show how to compute things like Bayes Factors and LOO and WAIC for model comparison there.

**Comment by TannerSorensen** [comment]
I see no problem with citing this paper in the contexts we have in the paper. Sven seems to agree.
