### ISSUE TITLE
multivariate LMM

### ISSUE THREAD

**Issue by naarkhoo** [vasishth/BayesLMMTutorial#7]
I wonder how I can vectorize 

```
for (i in 1:N)
    rt[i] ~ lognormal(X[i] * beta + Z_u[i] * u[subj[i]] + Z_w[i] * w[item[i]], sigma_e);
}

```

and make it suitable for a multivariate lmm ? I am trying to modify your varying-slope/varying-intercept/no-correlation for a multivariate regression.

Thanks.

**Comment by vasishth** [comment]
Did you look at the matrix version of the LMM formulation in the Sorensen et al paper? It's in the appendix. This is much more efficient and faster than the above formulation, which was presented only for didactic reasons.
